<?php 
    session_start();

    if (isset($_SESSION['id']) && isset($_SESSION['employee_id'])) {
        if ($_SESSION['employee_id'] == 'rootadmin1') {
            header('Location:admin.php');
        }
?>
<!DOCTYPE html>
    <html>
        <head>
            <title>Samadhaan</title>
            <link rel="stylesheet" type="text/css" href="style.css">
        </head>
        <body>
            <div id="greeting">
                <h1 style="font-size:30px;">Hello, <?php echo $_SESSION['name']; ?>!</h1>
                <a href="logout.php">Logout</a>
                <a href="past.php">My Concerns</a>
            </div>
            <form action="submit.php" style="position:relative; top: 6%;" method="POST" enctype="multipart/form-data">
                <h2>Log Your Concern</h2>
                <label for="housetype">House Type</label>
                <select name="house-type" id="house-type">
                    <option value="A">A</option>
                    <option value="B">B</option>
                    <option value="C">C</option>
                    <option value="D">D</option>
                    <option value="F">F</option>
                    <option value="H">H</option>
                    <option value="G">G</option>
                    <option value="TRT">TRT</option>
                    <option value="JSQ">JSQ</option>
                    <option value="SRT">SRT</option>
                    <option value="MF">MF</option>
                    <option value="GLF">GLF</option>
                    <option value="FLF">FLF</option>
                    <option value="SLB">SLB</option>
                    <option value="TLF">TLF</option>
                    <option value="TLB">TLB</option>
                    <option value="TRB">TRB</option>
                    <option value="TRF">TRF</option>
                </select>
                <label for="housenumber">House Number</label>
                <select name="house-number" id="house-number">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="6">6</option>
                    <option value="7">7</option>
                    <option value="8">8</option>
                    <option value="9">9</option>
                    <option value="10">10</option>
                    <option value="11">11</option>
                    <option value="12">12</option>
                </select><br><br>
                <script>
                    const houseNumbers = {"A":[{value:1,desc:"1"},
                                            {value:2,desc:"2"},
                                            {value:3,desc:"3"},
                                            {value:4,desc:"4"},
                                            {value:5,desc:"5"},
                                            {value:6,desc:"6"},
                                            {value:7,desc:"7"},
                                            {value:8,desc:"8"},
                                            {value:9,desc:"9"},
                                            {value:10,desc:"10"},
                                            {value:11,desc:"11"},
                                            {value:12,desc:"12"}],
                                        "B":[{value:1,desc:"1"},
                                            {value:2,desc:"2"},
                                            {value:3,desc:"3"},
                                            {value:4,desc:"4"},
                                            {value:5,desc:"5"},
                                            {value:6,desc:"6"},
                                            {value:7,desc:"7"},
                                            {value:8,desc:"8"},
                                            {value:9,desc:"9"},
                                            {value:10,desc:"10"},
                                            {value:11,desc:"11"},
                                            {value:12,desc:"12"}],
                                        "C":[{value:1,desc:"1"},
                                            {value:2,desc:"2"},
                                            {value:3,desc:"3"},
                                            {value:4,desc:"4"},
                                            {value:5,desc:"5"},
                                            {value:6,desc:"6"},
                                            {value:7,desc:"7"},
                                            {value:8,desc:"8"},
                                            {value:9,desc:"9"},
                                            {value:10,desc:"10"},
                                            {value:11,desc:"11"},
                                            {value:12,desc:"12"}],
                                        "D":[{value:1,desc:"1"},
                                            {value:2,desc:"2"},
                                            {value:3,desc:"3"},
                                            {value:4,desc:"4"},
                                            {value:5,desc:"5"},
                                            {value:6,desc:"6"},
                                            {value:7,desc:"7"},
                                            {value:8,desc:"8"},
                                            {value:9,desc:"9"},
                                            {value:10,desc:"10"},
                                            {value:11,desc:"11"},
                                            {value:12,desc:"12"}],
                                        "F":[{value:"1A",desc:"1A"},
                                            {value:"1B",desc:"2B"},
                                            {value:"2A",desc:"2A"},
                                            {value:"2B",desc:"2B"},
                                            {value:"3A",desc:"3A"},
                                            {value:"3B",desc:"3B"},
                                            {value:"4A",desc:"4A"},
                                            {value:"4B",desc:"4B"},
                                            {value:"5A",desc:"5A"},
                                            {value:"5B",desc:"5B"},
                                            {value:"6A",desc:"6A"},
                                            {value:"6B",desc:"6B"},
                                            {value:"7A",desc:"7A"},
                                            {value:"7B",desc:"7B"},
                                            {value:"8A",desc:"8A"},
                                            {value:"8B",desc:"8B"},
                                            {value:"9A",desc:"9A"},
                                            {value:"9B",desc:"9B"},
                                            {value:"10A",desc:"10A"},
                                            {value:"10B",desc:"10B"},
                                            {value:"11A",desc:"11A"},
                                            {value:"11B",desc:"11B"},
                                            {value:"12A",desc:"12A"},
                                            {value:"12B",desc:"12B"},
                                            {value:"13A",desc:"13A"},
                                            {value:"13B",desc:"13B"},
                                            {value:"14A",desc:"14A"},
                                            {value:"14B",desc:"14B"},
                                            {value:"15A",desc:"15A"},
                                            {value:"15B",desc:"15B"},
                                            {value:"16A",desc:"16A"},
                                            {value:"16B",desc:"16B"},
                                            {value:"17A",desc:"17A"},
                                            {value:"17B",desc:"17B"},
                                            {value:"18A",desc:"18A"},
                                            {value:"18B",desc:"18B"},
                                            {value:"19A",desc:"19A"},
                                            {value:"19B",desc:"19B"},
                                            {value:"20A",desc:"20A"},
                                            {value:"20B",desc:"20B"},
                                            {value:"21A",desc:"21A"},
                                            {value:"21B",desc:"21B"},
                                            {value:"22A",desc:"22A"},
                                            {value:"22B",desc:"22B"},
                                            {value:"23A",desc:"23A"},
                                            {value:"23B",desc:"23B"},
                                            {value:"24A",desc:"24A"},
                                            {value:"24B",desc:"24B"},
                                            {value:"25A",desc:"25A"},
                                            {value:"25B",desc:"25B"},
                                            {value:"26A",desc:"26A"},
                                            {value:"26B",desc:"26B"},
                                            {value:"27A",desc:"27A"},
                                            {value:"27B",desc:"27B"}],
                                        "H":[{value:"1A",desc:"1A"},
                                            {value:"1B",desc:"1B"},
                                            {value:"1C",desc:"1C"},
                                            {value:"1D",desc:"1D"},
                                            {value:"2A",desc:"2A"},
                                            {value:"2B",desc:"2B"},
                                            {value:"2C",desc:"2C"},
                                            {value:"2D",desc:"2D"},
                                            {value:"3A",desc:"3A"},
                                            {value:"3B",desc:"3B"},
                                            {value:"3C",desc:"3C"},
                                            {value:"3D",desc:"3D"},
                                            {value:"4A",desc:"4A"},
                                            {value:"4B",desc:"4B"},
                                            {value:"4C",desc:"4C"},
                                            {value:"4D",desc:"4D"},
                                            {value:"5A",desc:"5A"},
                                            {value:"5B",desc:"5B"},
                                            {value:"5C",desc:"5C"},
                                            {value:"5D",desc:"5D"},
                                            {value:"6A",desc:"6A"},
                                            {value:"6B",desc:"7B"},
                                            {value:"6C",desc:"6C"},
                                            {value:"6D",desc:"6D"},
                                            {value:"7A",desc:"7A"},
                                            {value:"7B",desc:"7B"},
                                            {value:"7C",desc:"7C"},
                                            {value:"7D",desc:"7D"},
                                            {value:"8A",desc:"8A"},
                                            {value:"8B",desc:"8B"},
                                            {value:"8C",desc:"8C"},
                                            {value:"8D",desc:"8D"},
                                            {value:"9A",desc:"9A"},
                                            {value:"9B",desc:"9B"},
                                            {value:"9C",desc:"9C"},
                                            {value:"9D",desc:"9D"},
                                            {value:"17A",desc:"17A"},
                                            {value:"17B",desc:"17B"},
                                            {value:"17C",desc:"17C"},
                                            {value:"17D",desc:"17D"},
                                            {value:"18A",desc:"18A"},
                                            {value:"18B",desc:"18B"},
                                            {value:"18C",desc:"18C"},
                                            {value:"18D",desc:"18D"},
                                            {value:"19A",desc:"19A"},
                                            {value:"19B",desc:"19B"},
                                            {value:"19C",desc:"19C"},
                                            {value:"19D",desc:"19D"},
                                            {value:"20A",desc:"20A"},
                                            {value:"20B",desc:"20B"},
                                            {value:"20C",desc:"20C"},
                                            {value:"20D",desc:"20D"},
                                            {value:"21A",desc:"21A"},
                                            {value:"21B",desc:"21B"},
                                            {value:"21C",desc:"21C"},
                                            {value:"21D",desc:"21D"},
                                            {value:"22A",desc:"22A"},
                                            {value:"22B",desc:"22B"},
                                            {value:"22C",desc:"22C"},
                                            {value:"22D",desc:"22D"},
                                            {value:"23A",desc:"23A"},
                                            {value:"23B",desc:"23B"},
                                            {value:"23C",desc:"23C"},
                                            {value:"23D",desc:"23D"},
                                            {value:"24A",desc:"24A"},
                                            {value:"24B",desc:"24B"},
                                            {value:"24C",desc:"24C"},
                                            {value:"24D",desc:"24D"},
                                            {value:"25A",desc:"25A"},
                                            {value:"25B",desc:"25B"},
                                            {value:"25C",desc:"25C"},
                                            {value:"25D",desc:"25D"},
                                            {value:"26A",desc:"26A"},
                                            {value:"26B",desc:"26B"},
                                            {value:"26C",desc:"26C"},
                                            {value:"26D",desc:"26D"},
                                            {value:"27A",desc:"27A"},
                                            {value:"27B",desc:"27B"},
                                            {value:"27C",desc:"27C"},
                                            {value:"27D",desc:"27D"},
                                            {value:"28A",desc:"28A"},
                                            {value:"28B",desc:"28B"},
                                            {value:"28C",desc:"28C"},
                                            {value:"28D",desc:"28D"},
                                            {value:"29A",desc:"29A"},
                                            {value:"29B",desc:"29B"},
                                            {value:"29C",desc:"29C"},
                                            {value:"29D",desc:"29D"},
                                            {value:"30A",desc:"30A"},
                                            {value:"30B",desc:"30B"},
                                            {value:"30C",desc:"30C"},
                                            {value:"30D",desc:"30D"},
                                            {value:"31A",desc:"31A"},
                                            {value:"31B",desc:"31B"},
                                            {value:"31C",desc:"31C"},
                                            {value:"31D",desc:"31D"},
                                            {value:"32A",desc:"32A"},
                                            {value:"32B",desc:"32B"},
                                            {value:"33C",desc:"32C"},
                                            {value:"33D",desc:"33D"},
                                            {value:"34A",desc:"34A"},
                                            {value:"34B",desc:"34B"},
                                            {value:"34C",desc:"34C"},
                                            {value:"34D",desc:"34D"},
                                            {value:"35A",desc:"35A"},
                                            {value:"35B",desc:"35B"},
                                            {value:"35C",desc:"35C"},
                                            {value:"35D",desc:"35D"},
                                            {value:"36A",desc:"36A"},
                                            {value:"36B",desc:"36B"},
                                            {value:"36C",desc:"36C"},
                                            {value:"36D",desc:"36D"},
                                            {value:"37A",desc:"37A"},
                                            {value:"37B",desc:"37B"},
                                            {value:"37C",desc:"37C"},
                                            {value:"37D",desc:"37D"},
                                            {value:"38A",desc:"38A"},
                                            {value:"38B",desc:"38B"},
                                            {value:"38C",desc:"38C"},
                                            {value:"38D",desc:"38D"},
                                            {value:"39A",desc:"39A"},
                                            {value:"39B",desc:"39B"},
                                            {value:"39C",desc:"39C"},
                                            {value:"39D",desc:"39D"},
                                            {value:"40A",desc:"40A"},
                                            {value:"40B",desc:"40B"},
                                            {value:"40C",desc:"40C"},
                                            {value:"40D",desc:"40D"}],
                                        "G":[{value:"1A",desc:"1A"},
                                            {value:"1B",desc:"1B"},
                                            {value:"1C",desc:"1C"},
                                            {value:"1D",desc:"1D"},
                                            {value:"2A",desc:"2A"},
                                            {value:"2B",desc:"2B"},
                                            {value:"2C",desc:"2C"},
                                            {value:"2D",desc:"2D"},
                                            {value:"3A",desc:"3A"},
                                            {value:"3B",desc:"3B"},
                                            {value:"3C",desc:"3C"},
                                            {value:"3D",desc:"3D"},
                                            {value:"4A",desc:"4A"},
                                            {value:"4B",desc:"4B"},
                                            {value:"4C",desc:"4C"},
                                            {value:"4D",desc:"4D"},
                                            {value:"5A",desc:"5A"},
                                            {value:"5B",desc:"5B"},
                                            {value:"5C",desc:"5C"},
                                            {value:"5D",desc:"5D"},
                                            {value:"6A",desc:"6A"},
                                            {value:"6B",desc:"7B"},
                                            {value:"6C",desc:"6C"},
                                            {value:"6D",desc:"6D"},
                                            {value:"7A",desc:"7A"},
                                            {value:"7B",desc:"7B"},
                                            {value:"7C",desc:"7C"},
                                            {value:"7D",desc:"7D"},
                                            {value:"8A",desc:"8A"},
                                            {value:"8B",desc:"8B"},
                                            {value:"8C",desc:"8C"},
                                            {value:"8D",desc:"8D"},
                                            {value:"9A",desc:"9A"},
                                            {value:"9B",desc:"9B"},
                                            {value:"9C",desc:"9C"},
                                            {value:"9D",desc:"9D"}],
                                        "TRT":[{value:"1A",desc:"1A"},
                                            {value:"1B",desc:"1B"},
                                            {value:"2A",desc:"2A"},
                                            {value:"2B",desc:"2B"},
                                            {value:"3A",desc:"3A"},
                                            {value:"3B",desc:"3B"}],
                                        "MF":[{value:1,desc:"1"},
                                            {value:2,desc:"2"},
                                            {value:3,desc:"3"},
                                            {value:4,desc:"4"}],
                                        "GLF":[{value:1,desc:"1"},
                                            {value:2,desc:"2"},
                                            {value:3,desc:"3"},
                                            {value:4,desc:"4"}],
                                        "FLF":[{value:5,desc:"5"},
                                            {value:6,desc:"6"},
                                            {value:7,desc:"7"},
                                            {value:8,desc:"8"}],
                                        "SLB":[{value:9,desc:"9"},
                                            {value:10,desc:"10"},
                                            {value:11,desc:"11"},
                                            {value:12,desc:"12"}],
                                        "TLF":[{value:9,desc:"9"}],
                                        "TLB":[{value:10,desc:"10"}],
                                        "TRB":[{value:11,desc:"11"}],
                                        "TRF":[{value:12,desc:"12"}],
                                         "SRT":[{value:1,desc:"1"},
                                            {value:2,desc:"2"},
                                            {value:3,desc:"3"},
                                            {value:4,desc:"4"},
                                            {value:5,desc:"5"},
                                            {value:6,desc:"6"},
                                            {value:7,desc:"7"},
                                            {value:8,desc:"8"},
                                            {value:9,desc:"9"},
                                            {value:10,desc:"10"},
                                            {value:11,desc:"11"},
                                            {value:12,desc:"12"},
                                            {value:13,desc:"13"},
                                            {value:14,desc:"14"},
                                            {value:15,desc:"15"},
                                            {value:16,desc:"16"},
                                            {value:17,desc:"17"},
                                            {value:18,desc:"18"},
                                            {value:19,desc:"19"},
                                            {value:20,desc:"20"},
                                            {value:21,desc:"21"},
                                            {value:22,desc:"22"},
                                            {value:23,desc:"23"},
                                            {value:24,desc:"24"},
                                            {value:25,desc:"25"},
                                            {value:26,desc:"26"},
                                            {value:27,desc:"27"},
                                            {value:28,desc:"28"},
                                            {value:29,desc:"29"},
                                            {value:30,desc:"30"},
                                            {value:31,desc:"31"},
                                            {value:32,desc:"32"},
                                            {value:33,desc:"33"},
                                            {value:34,desc:"34"},
                                            {value:35,desc:"35"},
                                            {value:36,desc:"36"},
                                            {value:37,desc:"37"},
                                            {value:38,desc:"38"},
                                            {value:39,desc:"39"},
                                            {value:40,desc:"40"},
                                            {value:41,desc:"41"},
                                            {value:42,desc:"42"},
                                            {value:43,desc:"43"},
                                            {value:44,desc:"44"},
                                            {value:45,desc:"45"},
                                            {value:46,desc:"46"},
                                            {value:47,desc:"47"},
                                            {value:48,desc:"48"},
                                            {value:49,desc:"49"},
                                            {value:50,desc:"50"},
                                            {value:51,desc:"51"},
                                            {value:52,desc:"52"},
                                            {value:53,desc:"53"},
                                            {value:54,desc:"54"},
                                            {value:55,desc:"55"},
                                            {value:56,desc:"56"},
                                            {value:57,desc:"57"},
                                            {value:58,desc:"58"},
                                            {value:59,desc:"59"},
                                            {value:60,desc:"60"},
                                            {value:61,desc:"61"},
                                            {value:62,desc:"62"},
                                            {value:63,desc:"63"},
                                            {value:64,desc:"64"},
                                            {value:65,desc:"65"},
                                            {value:66,desc:"66"},
                                            {value:67,desc:"67"},
                                            {value:68,desc:"68"},
                                            {value:69,desc:"69"},
                                            {value:70,desc:"70"},
                                            {value:71,desc:"71"},
                                            {value:72,desc:"72"},
                                            {value:73,desc:"73"},
                                            {value:74,desc:"74"},
                                            {value:75,desc:"75"},
                                            {value:76,desc:"76"},
                                            {value:77,desc:"77"},
                                            {value:78,desc:"78"},
                                            {value:79,desc:"79"},
                                            {value:80,desc:"80"},
                                            {value:81,desc:"81"},
                                            {value:82,desc:"82"}],
                                        "JSQ":[{value:"1A",desc:"1A"},
                                            {value:"1B",desc:"1B"},
                                            {value:"2A",desc:"2A"},
                                            {value:"2B",desc:"2B"},
                                            {value:"3A",desc:"3A"},
                                            {value:"3B",desc:"3B"},
                                            {value:"4A",desc:"4A"},
                                            {value:"4B",desc:"4B"}]};
                                            

                    const houseNumber = document.querySelector('[name=house-number]');
                    document.querySelector('[name=house-type]').addEventListener('change', function(e) {
                        houseNumber.innerHTML = houseNumbers[this.value].reduce((acc, elem) => `${acc}<option value="${elem.value}">${elem.desc}</option>`, "");
                    });
                </script>
                <label for="category">Category</label>
                <select name="category" id="concern-category">
                    <option value="category">Category</option>
                    <option value="civil">Civil</option>
                    <option value="electrical">Electrical</option>
                    <option value="plumbing">Plumbing</option>
                    <option value="housekeeping">Housekeeping</option>
                    <option value="others">Others</option>
                    </optgroup>
                </select><br><br>
                <label>Explain Your Concern</label><br>
                <textarea name="concern" id="concern" rows="10" cols="50"></textarea><br>
                <label>Upload Photo</label>
                <input type='file' name='file' />
                <button type="submit" style="float: none; width: 100%;">Submit Concern</button>
            </form>
        </body>
    </html>
<?php 
    }else{
        header("Location: index.php");
        exit();
    }
?>